[package]
name = "minifetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
num-traits = "0.2.15"
owo-colors = "3.5.0"
